import type { Resume } from "@/lib/schema";

export const SAMPLE_RESUME: Resume = {
  meta: {
    id: "sample",
    name: "Sample Resume",
    template: "chronos",
    color: "#000000",
    font: "geist",
    fontSize: "medium",
    spacing: "normal",
    margin: "normal",
    theme: "light",
    sectionOrder: [
      "personalInfo", "summary", "experience", "education",
      "skills", "certifications", "projects", "languages",
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  personalInfo: {
    firstName: "Sarah",
    lastName: "Chen",
    email: "sarah.chen@example.com",
    phone: "+1 (555) 123-4567",
    location: "San Francisco, CA",
    title: "Senior Product Designer",
    summary: "",
    website: "https://sarahchen.design",
    linkedin: "linkedin.com/in/sarahchen",
    github: "github.com/sarahchen",
    photo: "",
  },
  summary:
    "Senior Product Designer with 8+ years of experience leading design for B2B SaaS platforms. Proven track record of shipping products that drive measurable business impact. Expert in end-to-end product design, design systems, and cross-functional collaboration.",
  experience: [
    {
      id: "exp-1",
      company: "Figma Inc.",
      position: "Senior Product Designer",
      location: "San Francisco, CA",
      startDate: { month: 3, year: 2021 },
      current: true,
      description: "",
      bullets: [
        "Led redesign of the design system, reducing component creation time by 60% and improving cross-team consistency across 4 product lines",
        "Drove 25% increase in user activation through end-to-end redesign of onboarding flow, A/B tested with 50K+ users",
        "Established design review process adopted by 12-person team, reducing design-to-dev handoff issues by 40%",
        "Mentored 3 junior designers through structured growth program with 100% promotion rate",
      ],
    },
    {
      id: "exp-2",
      company: "Airbnb",
      position: "Product Designer II",
      location: "Remote",
      startDate: { month: 6, year: 2018 },
      endDate: { month: 2, year: 2021 },
      current: false,
      description: "",
      bullets: [
        "Designed and shipped host payout system serving 2M+ hosts, achieving 98% satisfaction score",
        "Reduced support ticket volume by 35% by redesigning the host financial dashboard for clarity",
        "Collaborated with 3 engineering teams to implement new payment feature, shipped on schedule",
      ],
    },
  ],
  education: [
    {
      id: "edu-1",
      school: "Carnegie Mellon University",
      degree: "Bachelor of Science",
      field: "Human-Computer Interaction",
      location: "Pittsburgh, PA",
      startDate: { month: 9, year: 2014 },
      endDate: { month: 5, year: 2018 },
      current: false,
      gpa: "3.8",
      honors: "Dean's List, Tau Beta Pi Honor Society",
    },
  ],
  skills: [
    {
      id: "skill-1",
      category: "Design",
      skills: ["Product Design", "UX Research", "Design Systems", "Prototyping", "Interaction Design"],
      level: 5,
    },
    {
      id: "skill-2",
      category: "Tools",
      skills: ["Figma", "Sketch", "Principle", "After Effects", "Framer"],
      level: 4,
    },
    {
      id: "skill-3",
      category: "Code",
      skills: ["HTML/CSS", "React", "TypeScript", "Tailwind", "Storybook"],
      level: 3,
    },
  ],
  certifications: [
    {
      id: "cert-1",
      name: "Google UX Design Certificate",
      issuer: "Google / Coursera",
      date: { month: 12, year: 2022 },
      url: "",
      description: "",
    },
  ],
  projects: [
    {
      id: "proj-1",
      name: "DesignOps Dashboard",
      description: "Internal tool for tracking design system usage, component adoption, and design review metrics across teams.",
      url: "",
      technologies: ["Figma API", "React", "D3.js", "Supabase"],
      startDate: { month: 1, year: 2023 },
      current: true,
    },
  ],
  languages: [
    { id: "lang-1", name: "English", proficiency: "native" },
    { id: "lang-2", name: "Mandarin", proficiency: "fluent" },
    { id: "lang-3", name: "Japanese", proficiency: "basic" },
  ],
  references: [],
  customSections: [],
};
